### ISSUE TITLE
Remove CSS templates

### ISSUE THREAD

**Issue by alfonsogarciacaro** [alfonsogarciacaro/vscode-template-fsharp-highlight#1]
They don't work well with F# interpolated strings because the angled brackets open holes.

**Comment by texastoland** [comment]
Alternatively I wonder if there's a way to dynamically replace `{`/`}` with `{{`/`}}` in CSS and similar grammars 🧐

**Comment by texastoland** [comment]
[Here](https://github.com/microsoft/vscode/blob/main/extensions/css/syntaxes/css.tmLanguage.json)'s the bundled CSS syntax assuming they aren't using [PostCSS](https://marketplace.visualstudio.com/items?itemName=csstools.postcss) instead (but it shouldn't matter). You should be able to injeect an additional grammar that only provides `{{` and `}}` for CSS (there are 8 different scopes for each).

**Comment by alfonsogarciacaro** [comment]
Thanks @texastoland! That's a very good point. However, since this extension is very simple atm and CSS templates may not be so useful in F#, let's remove them and we can revisit later if necessary 👍
