### ISSUE TITLE
Enable next line coloring

### ISSUE THREAD

**Issue by AngelMunoz** [alfonsogarciacaro/vscode-template-fsharp-highlight#2]
Sorry to bother you Alfonso 😅 (seems I'm good at that)
I'm exploring right now the Elmish.Lit goodies (Yay for Html in F#)  but sems that fantomas will move to the next line this kinds of strings, not sure if that can be fixed here or should be reported to fantomas itself
![image](https://user-images.githubusercontent.com/8684875/130325686-c427fcda-addd-48d1-8aae-a4734575e056.png)

otherwise, if you put it on the same line, it works wonders

**Comment by alfonsogarciacaro** [comment]
Hmm, looks like regex patterns in textmate grammars [cannot span across lines](https://github.com/microsoft/vscode-textmate/issues/41#issuecomment-344294298). We need to modify the grammar so it also includes a nested pattern when `$"""` appears in the next line.

**Comment by alfonsogarciacaro** [comment]
I think I fixed it :) Can you please check with v0.0.2 when it becomes available in the marketplace?

**Comment by AngelMunoz** [comment]
Yep! all working good, thanks!
![image](https://user-images.githubusercontent.com/8684875/130329075-e8dc853b-4da3-4712-af12-1f74fa5b9460.png)

**Comment by texastoland** [comment]
I fixed this better with a test script for edge cases! PR incoming 🚀
