### ISSUE TITLE
Code between bracket should be highlighted

### ISSUE THREAD

**Issue by MangelMaxime** [alfonsogarciacaro/vscode-template-fsharp-highlight#7]
![image](https://user-images.githubusercontent.com/4760796/136602732-b27f6d77-6a7e-42da-a18a-3c00814dff49.png)

Sometimes the brackets are mandatory for example:

```fs
let sb = new StringBuilder()

sb.WriteLine (html "<tbody>")
```

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @MangelMaxime! Could you please try with latest release (1.5)? Both of the issues you reported should be fixed 👍
