### ISSUE TITLE
Add support for pattern html <@ """<div>hi</div>""" @>

### ISSUE THREAD

**Issue by albertwoo** [alfonsogarciacaro/vscode-template-fsharp-highlight#9]
Can we add this pattern so we can:
```fsharp
let congratulation =
      Template.html
          <@ $"""
              <h1 onclick="{increase}">Congratulations! You made it!!!</h1>
          """ @>
```

The reason I use quotaion is because I can get the expression of the string and the interop holes so I can parse the plain string to a typed dom tree. I use this in my library Fun.Blazor: https://github.com/slaveOftime/Fun.Blazor/blob/master/Fun.Blazor.Docs.Wasm/Pages/HelperFunctions/HtmlTemplateDemo.fs

I know I can do this as a workround:
```fsharp
let congratulation =
      Template.html
          <@ Template.html // This will work but it requires more typing
                 $"""
                    <h1 onclick="{increase}">Congratulations! You made it!!!</h1>
                  """ @>
```

Or can we expose a VSCode settings to let extension user to add patterns?

**Comment by alfonsogarciacaro** [comment]
Unfortunately having custom patterns through settings may be tricky. As far as I know VS Code extensions need to provide the grammars in JSON formats in advance and they cannot be swapped on the fly.

If you just need to get the string and the holes you can do it by making `Template.html` accept `FormattableString`:

```fsharp
open System

module Template =
    let html (html: FormattableString) =
        printfn $"The string is: {html.Format}"
        printfn $"And the arguments are: {html.GetArguments()}"

let world = "world"
Template.html $"<h1>Hello {world} {2 + 2} times!</h1>"
```

**Comment by albertwoo** [comment]
Thanks for your suggestion! It works greate👍
